### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [postajob/gtm_view#1]
Thank you for submitting template to the gallery. However, there are a few issues that needs to be resolved ahead of approving the template for the gallery.

1) The SHA hash in manifest should be a valid one. Please update with valid SHA hash without which we cannot approve the template.
2) The documentation link provided in manifest file [http://postajob.io/gtm](http://postajob.io/gtm) is not valid. We are seeing "404 page not found error". Please resolve the issue.
3) The test assertion for the template fails with error "gtmOnSuccess has not been called.
". Please provide valid mock tests.

**Comment by goffle** [comment]
Updated Sha
Fixed documentation Link
Fixed test
